#!/usr/bin/env python3
"""
============================================================
 🎨 二次元角色转换器 - PNG → ESP32 C Header
 Image to Chibi Character Converter
============================================================

功能:
 1. 将 PNG/JPG 图像转换为 ESP32 OLED 可用的 C 数组
 2. 支持批量转换 (一个角色多个表情)
 3. 自动缩放、二值化 (OLED) 或量化 (TFT)
 4. 生成可直接 #include 的 .h 文件
 5. 预览转换效果

用法:
 python image_to_character.py --input ./my_character/ --output ../firmware/characters/
 python image_to_character.py --input happy.png --name my_chibi --expression happy
 python image_to_character.py --batch expressions.json --output ./output/
"""

import argparse
import json
import os
import sys
from pathlib import Path
from typing import List, Tuple, Optional
import struct
import math


# ==================== OLED 模式 (单色) ====================

def image_to_monochrome_bitmap(
    img_path: str,
    width: int = 40,
    height: int = 48,
    threshold: int = 128,
    invert: bool = False,
) -> Tuple[bytes, int, int]:
    """
    将图片转换为单色位图 (OLED 用)
    返回: (bitmap_bytes, actual_width, actual_height)
    """
    try:
        from PIL import Image
    except ImportError:
        print("❌ 需要 Pillow 库: pip install Pillow")
        sys.exit(1)

    img = Image.open(img_path).convert('L')  # 灰度

    # 缩放并居中裁剪
    img = resize_and_crop(img, width, height)

    # 二值化
    img = img.point(lambda p: 255 if p > threshold else 0)

    if invert:
        img = img.point(lambda p: 255 - p)

    # 转换为字节数组 (每个 bit 代表一个像素)
    pixels = list(img.getdata())
    byte_count = (width * height + 7) // 8
    bitmap = bytearray(byte_count)

    for i, pixel in enumerate(pixels):
        if pixel > 128:  # 白色 = 1
            byte_idx = i // 8
            bit_idx = 7 - (i % 8)
            bitmap[byte_idx] |= (1 << bit_idx)

    return bytes(bitmap), width, height


def image_to_rgb565_bitmap(
    img_path: str,
    width: int = 64,
    height: int = 64,
) -> Tuple[bytes, int, int]:
    """
    将图片转换为 RGB565 位图 (TFT 彩屏用)
    """
    try:
        from PIL import Image
    except ImportError:
        print("❌ 需要 Pillow 库: pip install Pillow")
        sys.exit(1)

    img = Image.open(img_path).convert('RGB')
    img = resize_and_crop(img, width, height)

    pixels = list(img.getdata())
    bitmap = bytearray(width * height * 2)
    idx = 0

    for r, g, b in pixels:
        # RGB888 → RGB565
        r5 = (r >> 3) & 0x1F
        g6 = (g >> 2) & 0x3F
        b5 = (b >> 3) & 0x1F
        rgb565 = (r5 << 11) | (g6 << 5) | b5
        bitmap[idx] = (rgb565 >> 8) & 0xFF
        bitmap[idx + 1] = rgb565 & 0xFF
        idx += 2

    return bytes(bitmap), width, height


def resize_and_crop(img, target_w: int, target_h: int):
    """缩放并居中裁剪"""
    from PIL import Image

    # 保持比例缩放
    img_ratio = img.width / img.height
    target_ratio = target_w / target_h

    if img_ratio > target_ratio:
        new_h = target_h
        new_w = int(target_h * img_ratio)
    else:
        new_w = target_w
        new_h = int(target_w / img_ratio)

    img = img.resize((new_w, new_h), Image.LANCZOS)

    # 居中裁剪
    left = (new_w - target_w) // 2
    top = (new_h - target_h) // 2
    img = img.crop((left, top, left + target_w, top + target_h))

    return img


# ==================== C Header 生成 ====================

def generate_header(
    character_name: str,
    frames: dict,  # {expression_name: bitmap_bytes}
    width: int,
    height: int,
    mode: str = 'monochrome',
    output_path: str = None,
) -> str:
    """生成可 #include 的 C header 文件"""

    safe_name = character_name.replace(' ', '_').replace('-', '_')
    guard = f"CHARACTER_{safe_name.upper()}_H"

    lines = [
        f"/* Auto-generated character: {character_name} */",
        f"/* Width: {width}, Height: {height}, Mode: {mode} */",
        f"/* Generated by image_to_character.py */",
        f"",
        f"#ifndef {guard}",
        f"#define {guard}",
        f"",
        f"#include <Arduino.h>",
        f"",
    ]

    # 表情帧
    exp_names = []
    frame_arrays = []

    for exp_name, bitmap in frames.items():
        exp_enum = f"CHAR_{safe_name.upper()}_{exp_name.upper()}"
        exp_names.append((exp_name, exp_enum))

        # 字节数组
        hex_str = ', '.join(f'0x{b:02X}' for b in bitmap)
        array_name = f"{safe_name}_{exp_name}"

        # 每行 16 字节
        hex_lines = []
        for i in range(0, len(hex_str.split(', ')), 16):
            chunk = ', '.join(hex_str.split(', ')[i:i+16])
            hex_lines.append(f"    {chunk}")

        frame_arrays.append((array_name, hex_lines))

    # 写入帧数据
    for array_name, hex_lines in frame_arrays:
        lines.append(f"// {array_name}")
        lines.append(f"static const uint8_t {array_name}[] PROGMEM = {{")
        lines.append(',\n'.join(hex_lines))
        lines.append("};")
        lines.append("")

    # 表情索引数组
    exp_count = len(exp_names)
    lines.append(f"// Expression index")
    lines.append(f"#define {safe_name.upper()}_EXP_COUNT {exp_count}")
    lines.append("")

    for i, (exp_name, exp_enum) in enumerate(exp_names):
        lines.append(f"#define {exp_enum} {i}")

    lines.append("")
    lines.append(f"static const uint8_t* {safe_name}_frames[{exp_count}] PROGMEM = {{")
    for _, (exp_name, _) in enumerate(exp_names):
        lines.append(f"    {safe_name}_{exp_name},")
    lines.append("};")
    lines.append("")

    # 角色结构体
    lines.append(f"// Character data")
    lines.append(f"static CharacterData {safe_name}_char PROGMEM = {{")
    lines.append(f'    .name = "{character_name}",')
    lines.append(f"    .frames = {safe_name}_frames,")
    lines.append(f"    .width = {width},")
    lines.append(f"    .height = {height},")
    lines.append(f"}};")
    lines.append("")
    lines.append(f"#endif // {guard}")

    header_content = '\n'.join(lines)

    if output_path:
        os.makedirs(os.path.dirname(output_path) or '.', exist_ok=True)
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(header_content)
        print(f"✅ 已生成: {output_path}")

    return header_content


# ==================== 预览 ====================

def preview_bitmap(bitmap: bytes, width: int, height: int):
    """在终端预览单色位图"""
    print(f"\n🖼️  预览 ({width}x{height}):")
    print("─" * (width + 2))
    for y in range(height):
        row = '│'
        for x in range(width):
            byte_idx = (y * width + x) // 8
            bit_idx = 7 - ((y * width + x) % 8)
            if byte_idx < len(bitmap) and (bitmap[byte_idx] & (1 << bit_idx)):
                row += '█'
            else:
                row += ' '
        row += '│'
        print(row)
    print("─" * (width + 2))


# ==================== 批量模式 ====================

def batch_convert(config_path: str, output_dir: str):
    """批量转换 (从 JSON 配置文件)"""
    with open(config_path, 'r', encoding='utf-8') as f:
        config = json.load(f)

    character_name = config.get('name', 'custom_character')
    mode = config.get('mode', 'monochrome')
    width = config.get('width', 40)
    height = config.get('height', 48)
    threshold = config.get('threshold', 128)
    invert = config.get('invert', False)

    frames = {}

    for exp in config.get('expressions', []):
        exp_name = exp['name']
        img_path = exp['image']

        if not os.path.exists(img_path):
            print(f"⚠️  跳过 {exp_name}: 文件不存在 {img_path}")
            continue

        print(f"🔄 处理 {exp_name}: {img_path}")

        if mode == 'rgb565':
            bitmap, w, h = image_to_rgb565_bitmap(img_path, width, height)
        else:
            bitmap, w, h = image_to_monochrome_bitmap(
                img_path, width, height, threshold, invert
            )

        frames[exp_name] = bitmap

        if config.get('preview', False):
            preview_bitmap(bitmap, w, h)

    if not frames:
        print("❌ 没有成功处理的帧!")
        return

    # 生成 header
    output_path = os.path.join(output_dir, f'{character_name}.h')
    generate_header(character_name, frames, width, height, mode, output_path)

    print(f"\n🎉 完成! 共 {len(frames)} 个表情帧")
    print(f"📁 输出: {output_path}")
    print(f"\n💡 使用方法:")
    print(f'   1. 将 {character_name}.h 复制到 firmware/characters/ 目录')
    print(f'   2. 在 firmware.ino 中添加:')
    print(f'      #include "characters/{character_name}.h"')
    print(f'   3. 使用: characterEngine.loadCharacter(&{character_name}_char);')


# ==================== 示例配置生成 ====================

def generate_example_config(output_path: str):
    """生成示例批量转换配置"""
    config = {
        "name": "my_chibi",
        "mode": "monochrome",
        "width": 40,
        "height": 48,
        "threshold": 128,
        "invert": False,
        "preview": True,
        "expressions": [
            {"name": "idle", "image": "./expressions/idle.png"},
            {"name": "happy", "image": "./expressions/happy.png"},
            {"name": "working", "image": "./expressions/working.png"},
            {"name": "worried", "image": "./expressions/worried.png"},
            {"name": "angry", "image": "./expressions/angry.png"},
            {"name": "sleep", "image": "./expressions/sleep.png"},
            {"name": "love", "image": "./expressions/love.png"},
            {"name": "greeting", "image": "./expressions/greeting.png"},
        ]
    }
    os.makedirs(os.path.dirname(output_path) or '.', exist_ok=True)
    with open(output_path, 'w', encoding='utf-8') as f:
        json.dump(config, f, ensure_ascii=False, indent=2)
    print(f"✅ 示例配置已生成: {output_path}")
    print(f"💡 请创建对应的表情 PNG 文件 (40x48 像素最佳)")


# ==================== CLI ====================

def main():
    parser = argparse.ArgumentParser(
        description='🎨 二次元角色转换器 - PNG → ESP32 C Header',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
使用示例:
  # 单表情转换
  python image_to_character.py -i happy.png -n my_chibi -e happy -o ./output/

  # 批量转换
  python image_to_character.py --batch expressions.json -o ./output/

  # 生成示例配置
  python image_to_character.py --example-config expressions.json

  # OLED模式 (默认 40x48)
  python image_to_character.py -i idle.png -n chibi -e idle --mode mono --size 40x48

  # TFT彩屏模式 (64x64 RGB565)
  python image_to_character.py -i idle.png -n chibi -e idle --mode rgb565 --size 64x64
        """
    )

    parser.add_argument('--input', '-i', help='输入图片路径')
    parser.add_argument('--name', '-n', default='custom_chibi', help='角色名称')
    parser.add_argument('--expression', '-e', default='idle',
                       choices=['idle','happy','working','worried','angry','sleep','love','greeting'],
                       help='表情名称')
    parser.add_argument('--output', '-o', default='./output/', help='输出目录')
    parser.add_argument('--mode', '-m', default='mono',
                       choices=['mono','rgb565'], help='颜色模式')
    parser.add_argument('--size', '-s', default='40x48', help='尺寸 WxH')
    parser.add_argument('--threshold', '-t', type=int, default=128, help='二值化阈值 (0-255)')
    parser.add_argument('--invert', action='store_true', help='反转颜色')
    parser.add_argument('--preview', '-p', action='store_true', help='终端预览')
    parser.add_argument('--batch', '-b', help='批量转换 (JSON配置)')
    parser.add_argument('--example-config', help='生成示例配置文件')

    args = parser.parse_args()

    # 生成示例配置
    if args.example_config:
        generate_example_config(args.example_config)
        return

    # 批量模式
    if args.batch:
        batch_convert(args.batch, args.output)
        return

    # 单图模式
    if not args.input:
        parser.print_help()
        print("\n❌ 需要 --input 或 --batch 参数")
        sys.exit(1)

    if not os.path.exists(args.input):
        print(f"❌ 文件不存在: {args.input}")
        sys.exit(1)

    # 解析尺寸
    w, h = map(int, args.size.split('x'))

    print(f"🔄 处理: {args.input}")
    print(f"   角色: {args.name}, 表情: {args.expression}")
    print(f"   模式: {args.mode}, 尺寸: {w}x{h}")

    if args.mode == 'rgb565':
        bitmap, w_out, h_out = image_to_rgb565_bitmap(args.input, w, h)
    else:
        bitmap, w_out, h_out = image_to_monochrome_bitmap(
            args.input, w, h, args.threshold, args.invert
        )

    print(f"   位图大小: {len(bitmap)} bytes ({w_out}x{h_out})")

    if args.preview and args.mode == 'mono':
        preview_bitmap(bitmap, w_out, h_out)

    # 生成 header
    output_path = os.path.join(args.output, f'{args.name}.h')
    generate_header(args.name, {args.expression: bitmap},
                    w_out, h_out, args.mode, output_path)

    print(f"\n🎉 完成!")


if __name__ == '__main__':
    main()
